title: "연맹 가이드"
description: "PNX 연맹 가이드"
url: "https://kingshot.wooju-home.org"
baseurl: ""

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

permalink: pretty

collections:
  guides:
    output: false

defaults:
  - scope:
      path: "_guides/beginner"
    values:
      category: beginner
  - scope:
      path: "_guides/events"
    values:
      category: events

exclude:
  - document
  - Gemfile.lock
  - README.md
  - node_modules
